[package]
name = "stream-download-storage-ext"
version = "0.1.0"
edition = "2024"
rust-version = "1.88.0"
authors = ["Pavel Litvinenko <gerasim13@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/aschey/stream-download-rs"
homepage = "https://github.com/aschey/stream-download-rs"
include = ["/src", "/tests", "LICENSE-MIT", "LICENSE-APACHE"]
categories = ["multimedia", "asynchronous", "caching"]
keywords = ["audio", "stream", "media", "cache"]
description = "Storage-backed cache implementations for stream-download"

[dependencies]
stream-download = { path = "../stream-download", features = ["temp-storage"] }
bytes = { workspace = true }
educe = { workspace = true }
parking_lot = { workspace = true }
reqwest = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
stream-download = { path = "../stream-download", features = ["temp-storage"] }
tokio = { workspace = true, features = ["rt", "macros"] }
tempfile = { workspace = true }

[features]
default = []

[lints]
workspace = true
